export const CHANGE_SCREEN = 'CHANGE_SCREEN';
export const CHANGE_SCREEN_COMPLETE = 'CHANGE_SCREEN_COMPLETE';

export const CHANGE_SELECTED_TEXT_FIELD = 'CHANGE_SELECTED_TEXT_FIELD';
export const CHANGE_TEXT_FIELD_INPUT = 'CHANGE_TEXT_FIELD_INPUT';
export const CLEAR_TEXT_FIELD_INPUT = 'CLEAR_TEXT_FIELD_INPUT';
