export const ADD_FADE_ANIMATION = 'ADD_FADE_ANIMATION';
export const REMOVE_FADE_ANIMATION = 'REMOVE_FADE_ANIMATION';
export const CHANGE_FADE_ANIMATION = 'CHANGE_FADE_ANIMATION';
export const COMPLETE_FADE_ANIMATION = 'COMPLETE_FADE_ANIMATION';
