export const ADD_ANIMATION = 'ADD_ANIMATION';
export const REMOVE_ANIMATION = 'REMOVE_ANIMATION';
export const CHANGE_ANIMATION = 'CHANGE_ANIMATION';
export const COMPLETE_ANIMATION = 'COMPLETE_ANIMATION';
